# Generated by Django 2.0.9 on 2018-10-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('title', models.CharField(blank=True, max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=100)),
                ('ownername', models.CharField(max_length=100)),
                ('server', models.CharField(max_length=100)),
                ('secret', models.CharField(max_length=100)),
                ('farm', models.IntegerField()),
                ('is_public', models.IntegerField()),
                ('is_friend', models.IntegerField()),
                ('is_family', models.IntegerField()),
                ('date_added', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'photos',
            },
        ),
    ]
