# Generated by Django 2.0.9 on 2018-10-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('no_photos', models.IntegerField()),
            ],
            options={
                'db_table': 'group',
            },
        ),
    ]
